linters:
    flake8:
    eslint:
        config: './.eslintrc.js'
    csslint:

files:
    ignore:
        - 'src/generated/*'
        - 'src/style.css'
        - 'webroot/bower_components/*'
        - 'dist/*'